name: Start/Stop AWS instance

on:
  workflow_call:
    inputs:
      mode:
        description: "Mode of operation: start or stop"
        type: string
        required: true

      runs-on-list:
        # See devops/actions/aws-ec2/action.yml for more details.
        description: "JSON string with array of objects with aws-type, runs-on, aws-ami, aws-spot, aws-disk, aws-timebomb, one-job properties"
        type: string
        required: true

    outputs:
      label:
        description: |
          In start mode, return 'runs-on' value from the input runs-on-list. We only
          support scenario where a single runner is created.
        value: ${{ jobs.aws.outputs.label }}

jobs:
  aws:
    runs-on: ubuntu-20.04
    environment: aws
    outputs:
      label: ${{ steps.aws-ec2.outputs.label }}

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            devops/actions/aws-ec2
      - name: Setup script
        run: |
          npm install ./devops/actions/aws-ec2
      - name: Start AWS EC2 runners
        id: aws-ec2
        uses: ./devops/actions/aws-ec2
        with:
          mode: ${{ inputs.mode }}
          runs-on-list: ${{ inputs.runs-on-list }}
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
